#! /bin/bash
### BEGIN INIT INFO
# Provides: 		interfaces
# Required-Start: 	$local_fs $network
# Required-Stop:	$local_fs $network
# Default-Start: 	2 3 4 5
# Default-Stop: 	0 1 6
# Description: 		interfaces
### END INIT INFO
 

/opt/tsinterface.sh
exit
